packages:
  - "deps/cr-sqlite/core"
  - "packages/browser-tests"
  - "packages/crsqlite-wasm"
  - "packages/node-allinone"
  - "packages/node-tests"
  - "packages/ws-browserdb"
  - "packages/ws-client"
  - "packages/ws-common"
  - "packages/ws-server"
  - "packages/ws-demo"
  - "packages/p2p"
  - "packages/react"
  - "packages/direct-connect-browser"
  - "packages/direct-connect-common"
  - "packages/direct-connect-nodejs"
  - "packages/rx-query"
  - "packages/rx-tbl"
  - "packages/xplat-api"
  - "packages/xplat-tests"
  - "packages/sandbox"
  - "packages/sandbox-node"
  - "tsbuild-all"
  - "deps/wa-sqlite"
