packages:
  - "../cr-sqlite/core"
  - "deps/wa-sqlite"
  - "../typed-sql/packages/cli"
  - "../typed-sql/packages/typed-sql"
  - "../typed-sql/packages/type-gen/pkg"
  - "../typed-sql/packages/type-gen-ts-adapter"
  - "packages/browser-tests"
  - "packages/crsqlite-wasm"
  - "packages/node-allinone"
  - "packages/node-tests"
  - "packages/ws-browserdb"
  - "packages/ws-client"
  - "packages/ws-common"
  - "packages/ws-demo"
  - "packages/ws-litefs"
  - "packages/ws-server"
  - "packages/p2p"
  - "packages/react"
  - "packages/direct-connect-browser"
  - "packages/direct-connect-common"
  - "packages/direct-connect-nodejs"
  - "packages/rx-query"
  - "packages/rx-tbl"
  - "packages/xplat-api"
  - "packages/xplat-tests"
  - "packages/sandbox"
  - "packages/sandbox-node"
  - "packages/id"
  - "tsbuild-all"
