declare -a pkgs=(
  "@vlcn.io/create"
  "@vlcn.io/crsqlite"
  "@vlcn.io/crsqlite-wasm"
  "@vlcn.io/crsqlite-allinone"
  "@vlcn.io/sync-p2p"
  "@vlcn.io/react"
  "@vlcn.io/direct-connect-browser"
  "@vlcn.io/direct-connect-common"
  "@vlcn.io/direct-connect-nodejs"
  "@vlcn.io/rx-tbl"
  "@vlcn.io/xplat-api"
  "@vlcn.io/wa-sqlite"
  "@vlcn.io/ws-common"
  "@vlcn.io/ws-server"
  "@vlcn.io/ws-client"
  "@vlcn.io/ws-litefs"
  "@vlcn.io/ws-browserdb"
  "@vlcn.io/typed-sql"
  "@vlcn.io/typed-sql-cli"
  "@vlcn.io/id"
)

# two packages have directory names mismatched with package names hence this array.
declare -a pkgslocal=(
  "@vlcn.io/create:../js/packages/create"
  "@vlcn.io/crsqlite:../cr-sqlite/core"
  "@vlcn.io/crsqlite-wasm:../js/packages/crsqlite-wasm"
  "@vlcn.io/crsqlite-allinone:../js/packages/node-allinone"
  "@vlcn.io/sync-p2p:../js/packages/p2p"
  "@vlcn.io/react:../js/packages/react"
  "@vlcn.io/direct-connect-browser:../js/packages/direct-connect-browser"
  "@vlcn.io/direct-connect-common:../js/packages/direct-connect-common"
  "@vlcn.io/direct-connect-nodejs:../js/packages/direct-connect-nodejs"
  "@vlcn.io/rx-tbl:../js/packages/rx-tbl"
  "@vlcn.io/xplat-api:../js/packages/xplat-api"
  "@vlcn.io/wa-sqlite:../js/packages/wa-sqlite"
  "@vlcn.io/ws-common:../js/packages/ws-common"
  "@vlcn.io/ws-server:../js/packages/ws-server"
  "@vlcn.io/ws-client:../js/packages/ws-client"
  "@vlcn.io/ws-litefs:../js/packages/ws-litefs"
  "@vlcn.io/ws-browserdb:../js/packages/ws-browserdb"
  "@vlcn.io/typed-sql:../typed-sql/packages/typed-sql"
  "@vlcn.io/typed-sql-cli:../typed-sql/packages/cli"
)
